# Generated by Django 4.2 on 2026-09-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('weight', 'Weight'), ('sound', 'Sound Activity')], max_length=50)),
                ('sensor_id', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='hive.hive')),
            ],
            options={
                'db_table': 'sensor_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['hive', '-timestamp'], name='sensor_data_hive_id_03749b_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor_type'], name='sensor_data_sensor__28185c_idx'),
        ),
    ]
