# Generated by Django 4.2 on 2026-09-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.FloatField(help_text='Quantity in kg')),
                ('honey_type', models.CharField(choices=[('raw', 'Raw'), ('processed', 'Processed'), ('organic', 'Organic'), ('multifloral', 'Multifloral')], max_length=100)),
                ('color_grade', models.CharField(blank=True, choices=[('extra_light', 'Extra Light'), ('light', 'Light'), ('amber', 'Amber'), ('dark', 'Dark')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='hive.hive')),
            ],
            options={
                'db_table': 'harvests',
                'ordering': ['-harvest_date'],
            },
        ),
    ]
