# Generated by Django 4.2 on 2026-09-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_data', models.CharField(max_length=500)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('scans', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='batch.honeybatch')),
            ],
            options={
                'db_table': 'qr_codes',
            },
        ),
    ]
