# Generated by Django 4.2 on 2026-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="qr_image_base64",
            field=models.TextField(blank=True, null=True),
        ),
    ]
