# Generated by Django 4.2 on 2026-09-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beekeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hive_type', models.CharField(choices=[('langstroth', 'Langstroth'), ('topbar', 'Top-bar'), ('warre', 'Warré')], max_length=50)),
                ('installation_date', models.DateField()),
                ('last_inspection', models.DateField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('population', models.IntegerField(default=0, help_text='Number of bees')),
                ('honey_frames', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='beekeeper.apiary')),
            ],
            options={
                'db_table': 'hives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiveHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity in percentage')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('bee_activity', models.IntegerField(help_text='Bee activity level 0-100')),
                ('disease_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='hive.hive')),
            ],
            options={
                'db_table': 'hive_health',
            },
        ),
    ]
