# Generated by Django 4.2 on 2026-09-12 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=255, unique=True)),
                ('origin', models.CharField(help_text='Origin/Apiary', max_length=255)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('block_number', models.IntegerField()),
                ('honey_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.FloatField(help_text='Quantity in kg')),
                ('quality_score', models.IntegerField(default=0, help_text='Quality score 0-100')),
                ('test_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockchain_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('transaction_type', models.CharField(choices=[('batch_creation', 'Batch Creation'), ('quality_check', 'Quality Check'), ('processing', 'Processing'), ('packaging', 'Packaging'), ('shipment', 'Shipment'), ('delivery', 'Delivery')], max_length=100)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
