# Generated by Django 4.2 on 2026-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('total_quantity', models.FloatField(help_text='Total quantity in kg')),
                ('honey_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('quality_tested', 'Quality Tested'), ('approved', 'Approved'), ('processing', 'Processing'), ('packaged', 'Packaged'), ('shipped', 'Shipped')], default='created', max_length=20)),
                ('quality_score', models.IntegerField(default=0, help_text='0-100')),
                ('batch_blockchain_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harvests', models.ManyToManyField(related_name='batches', to='harvest.harvest')),
            ],
            options={
                'db_table': 'honey_batches',
                'ordering': ['-created_at'],
            },
        ),
    ]
