# Generated by Django 4.2 on 2026-09-12 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('color_intensity', models.IntegerField()),
                ('aroma_grade', models.CharField(max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_test', to='batch.honeybatch')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_tests',
            },
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Processing temperature in Celsius')),
                ('duration', models.IntegerField(help_text='Processing duration in minutes')),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing', to='batch.honeybatch')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processing',
            },
        ),
    ]
